on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '30 6 * * 2,5'  # every Tuesday and Friday at 06:30

name: get-data

jobs:
  get-data:
    runs-on: ubuntu-latest
    concurrency:
      group: get-data-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pins, any::paws.storage, local::.

      - name: Restore poddr httr2 cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R/poddr
          key: ${{ runner.os }}-poddr-http-${{ hashFiles('.github/workflows/get-data.yaml') }}
          restore-keys: |
            ${{ runner.os }}-poddr-http-

      - name: Fetch and cache all podcast data
        run: |
          library(poddr)
          dir.create("data_cache", showWarnings = FALSE)
          update_cached_data(dir = "data_cache")
        shell: Rscript {0}

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy data to S3
        with:
          command: cp
          source: ./data_cache/
          destination: s3://jemsudatasets/podcaststats/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          flags: --recursive
