on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '30 6 * * 2,5'  # every tuesday and friday at 6:30

name: get-data

jobs:
  get-data:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: get-data-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pins, any::paws.storage, local::.

      - name: Get ATP data
        run: |
          library(poddr)
          dir.create("data_cache")
          atp_get_episodes()
        shell: Rscript {0}

      - name: Get Relay.fm data
        run: |
          library(poddr)
          relay_shows <- relay_get_shows()
          relay_get_episodes(relay_shows)
        shell: Rscript {0}

      - name: Get The Incomparable data
        run: |
          library(poddr)
          incomparable_shows <- incomparable_get_shows()
          incomparable_get_episodes(incomparable_shows)
        shell: Rscript {0}

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy data to s3
        with:
          command: cp
          source: ./data_cache/
          destination: s3://jemsudatasets/podcaststats/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          flags: --recursive
